<?php
/**
 * Admin panel — employee profile Salary tab: generated HRMS payslips with download.
 * Expects $conn (mysqli) and $ID (employees.ID) from view_profile_details / view_employee.
 */
if (!isset($conn) || !isset($ID) || intval($ID) <= 0) {
	return;
}

require_once __DIR__ . '/../../../api/inc/payslip_bootstrap.php';

$employeeId = intval($ID);
$salaryPayroll = api_payslip_service($conn);
$slips = $salaryPayroll->listEmployeeSlips($employeeId, 24);
$defaultCompanyId = $salaryPayroll->getDefaultQuoteCompanyId();
?>
<div class="panel-container show mt-3">
	<div class="panel-content p-0">
		<h5 class="px-3 pt-3 mb-2"><strong>My salary slips</strong></h5>
		<p class="px-3 text-muted small mb-2">Payslips generated by HR. Tap download to save your PDF.</p>
		<div class="table-responsive">
			<table class="table table-bordered table-hover table-striped w-100 mb-0">
				<thead>
					<tr>
						<th>Month</th>
						<th class="text-right">Gross</th>
						<th class="text-right">Deduction</th>
						<th class="text-right">Net</th>
						<th class="text-center">Action</th>
					</tr>
				</thead>
				<tbody>
<?php if (empty($slips)) { ?>
					<tr>
						<td colspan="5" class="text-center text-muted py-3">No salary slip has been generated for you yet.</td>
					</tr>
<?php } else {
	foreach ($slips as $s) {
		$slipId = intval($s['ID']);
		$period = date('M Y', mktime(0, 0, 0, intval($s['PayrollMonth']), 1, intval($s['PayrollYear'])));
		$hrPath = '';
		if ($defaultCompanyId > 0) {
			$token = $salaryPayroll->createPayslipShareToken($slipId, $defaultCompanyId);
			$hrPath = '../../api/download_employee_salary_slip.php?token=' . rawurlencode($token);
		}
?>
					<tr>
						<td><?php echo htmlspecialchars($period, ENT_QUOTES, 'UTF-8'); ?></td>
						<td class="text-right"><?php echo number_format(floatval($s['GrossSalary']), 2); ?></td>
						<td class="text-right"><?php echo number_format(floatval($s['TotalDeductions']), 2); ?></td>
						<td class="text-right"><?php echo number_format(floatval($s['NetSalary']), 2); ?></td>
						<td class="text-center">
<?php if ($hrPath !== '') { ?>
							<a class="btn btn-sm btn-primary" href="<?php echo htmlspecialchars($hrPath, ENT_QUOTES, 'UTF-8'); ?>" target="_blank" rel="noopener">Download PDF</a>
<?php } else { ?>
							<span class="text-muted small">Company not configured</span>
<?php } ?>
						</td>
					</tr>
<?php
	}
} ?>
				</tbody>
			</table>
		</div>
	</div>
</div>
